sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t didiyudha/docker-react .
script:
  - docker run -e CI=true stephengrider/docker-react npm run test -- --coverage
